[lkbridge]
type = websocket_client
connection_type = per_call_config
uri = ws://127.0.0.1:8091/media
protocols = media
connection_timeout = 1000
reconnect_interval = 500
reconnect_attempts = 2
enable_tcp_keepalives = yes
tcp_keepalive_time = 20
tcp_keepalive_interval = 10
tcp_keepalive_probes = 3
